### PR TITLE
Group dotfiles at the top of the list. (#39)

### PR DESCRIPTION
**Pull request by champagst**

### CODE REVIEW

**Comment by radiovisual** [comment]
Looking good! Nice work! I just tested your PR and everything seems to work the way it should, only just one thing: all of the files that are mentioned in the user-defined regular expression should also be grouped at the top, since that regular expression marks the files that users want to hide. You have grouped all the dotfiles at the top, but the `license` file (from the default RegExp: `^\.|^license|^appveyor\.yml$`) is not being grouped with the others:

image

**Comment by champagst** [comment]
That definitely makes more sense. I was looking at how the dot files were grouped at the top in a linux listing, but this allows more files to be hidden.

**Comment by radiovisual** [comment]
Awesome. Just tested it. Works great! Let's see if @sindresorhus and @jamestalmage agree.

**Comment by radiovisual** [comment]
@sindresorhus , I have been using this PR's version of the extension for the last 5 days. It works great! I would say it is ready to be merged.

**Comment by jamestalmage** [comment]
I have not tested it, but the code looks good to me. Since you've already been beta testing for 5 days, I'd say merge and ship it!

**Comment by sindresorhus** [comment]
Thanks @champagst :)

Published now. Should be updated in your Chrome's within an hour.

**Pull request merged**
