### PR TITLE
Readable regexes in options + validation

### PR DESCRIPTION
**Pull request by bfred-it**
## Changes

- Easier to read
- Easier to edit
- Easier to reset
- Drops duplicate "Hide files" title
- Instant validation

## Before and After

before

after

### CODE REVIEW

**Comment by bfred-it** [comment]
Instead of "leave empty to restore the default" I had thought of adding a reset button, but `window.confirm` doesn't work there and recreating it is a little bit more involved.

**Comment by bfred-it** [comment]
Is webext-options-sync worth adding? https://github.com/bfred-it/webext-options-sync/blob/master/webext-options-sync.js

Not particularly _needed_ but I think it would replace 3/4 functions in api.js and options.js. I feel like I'm reimplementing it inline :D

**Comment by sindresorhus** [comment]
Yes, go ahead and add it :)

**Comment by sindresorhus** [comment]
Looks very good. Much better UX now ❤️

**Comment by bfred-it** [comment]
It doesn't look like using `webext-options-sync` is possible as is, since it doesn't support:

- editing a field before saving (we trim the regex)
- accessing the defaults from the content script (we need them to reset the field).
   In my pkg, defaults are defined in the background and only accessed on the first install.

**Comment by bfred-it** [comment]
This is good to merge. The other I think is missing the option (which depends on this)

**Comment by sindresorhus** [comment]
Awesome! 👌

**Pull request merged**
