### PR TITLE
Add `Cargo.lock` as a hidden file

### PR DESCRIPTION
**Pull request by lffg**

### CODE REVIEW

**Comment by Turbo87** [comment]
I came here to submit the exact same PR 😅 

@sindresorhus can we help in some way to get this released?

**Comment by fregante** [comment]
Why cargo.lock instead of _all_ lockfiles?

**Comment by Turbo87** [comment]
@fregante what other lockfiles are you talking about? 🤔

**Comment by fregante** [comment]
`/\.lock$/`

**Comment by Turbo87** [comment]
🤷‍♂️  I could imagine that there might be legitimate cases of `*.lock` files, but I guess that would work too for 99.9% of cases

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/hide-files-on-github/releases/tag/21.9.16 (Coming to your computer soon)

**Comment by Turbo87** [comment]
❤️

**Pull request merged**
