### PR TITLE
Convert to TypeScript

### LINKED ISSUE #75: Convert to TypeScript
This would also let us use JSX and https://github.com/vadimdemedes/dom-chef

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #75 

- [x] JSX/dom-chef coming
- [x] Testing...

### CODE REVIEW

**Comment by bfred-it** [comment]
This seems to work correctly now.

**Comment by bfred-it** [comment]
Since this is a build step, do you want to go all the way and add browserify so we can properly bundle the dependencies?

**Comment by sindresorhus** [comment]
Yeah, although, Rollup or Webpack would probably be a better choice. They are more actively maintained.

**Comment by bfred-it** [comment]
This should be good to go

**Pull request merged**
