### PR TITLE
always dim and move toggle button to the top

### PR DESCRIPTION
**Pull request by radiovisual**
This moves the toggle button to the top, and simplifies the options page by removing the dim toggle (dim is always on, no matter what mode you are in).

### CODE REVIEW

**Comment by radiovisual** [comment]
The new options page:

image

**Comment by jamestalmage** [comment]
What if the toggle button was always there, and the option was just "hide by default"

**Comment by radiovisual** [comment]
Actually, yes, that is a better idea, because up to this point, and even more so now with this PR, we have essentially had two different toggle buttons, one on the UI (the "Show/hide" button), and one in the options.

Your idea simplifies things, and puts all the power into the toggle button. I like it.

**Comment by radiovisual** [comment]
Ok, I pushed a new commit. I love everything about this idea, because I was able to remove a lot of code (to simplify the codebase), but it also keeps the extension true to its name: `hide-files-on-github`. So now the toggle button is always there, and the option is to just ''hide by default", which is also better, because it keeps your "showing" or "hiding" encapsulated to the GitHub page you are viewing, instead of using the same global settings across all GitHub pages.

The new options page is now super sleek:

image

**Comment by jamestalmage** [comment]
Hmm. Does it default to hidden now? My thought was to leave a checkbox in options, that said 

- [x] hide by default 

When checked, the files would be hidden when you got to the page, and you must click to show them.

When unchecked, the files would be visible, but you could hide them with the button.

**Comment by radiovisual** [comment]
Yes, it defaults to hidden now. I feel like giving the option for users to "Show by default" defeats the purpose of the extension. I like the simple usability of one button that lets me show or hide the files. No need to add in another show/hide toggle on top of a show/hide toggle.

If we give them the option to "Show by default", then they will always need to visit the options to change the show/hide behavior, but they already have an option to change the show/hide behavior with one simple click of the "show/hide" toggle button on the UI, so adding in another toggle on top of a toggle feels like "too much toggle."

But I am totally open to suggestions, so if the vote goes to the "Hide by default" option, then I will happily add it in.

**Comment by jamestalmage** [comment]
Let's leave it the way you have it now.

**Comment by sindresorhus** [comment]
I'm ok with this as I never used the `Dim` option anyways.

**Comment by bfred-it** [comment]
I did use the `dim` option, I'm not sure of why the option to only have dim was removed :(

**Pull request merged**
