### PR TITLE
add div to toggle button to remove offset

### PR DESCRIPTION
**Pull request by mpfeil**
The **Show dotfiles** toggle button has an offset.
bildschirmfoto 2016-02-04 um 20 17 39

I have added  `<div class="btn-group">...</div>` to the toggle button to remove the offset and align the button.
bildschirmfoto 2016-02-04 um 20 18 36

### CODE REVIEW

**Comment by radiovisual** [comment]
nice catch. Github must have changed their markup recently.

**Comment by sindresorhus** [comment]
Can you instead add our button to the `New file`/`Find file` button group? That would look better too.

**Comment by mpfeil** [comment]
Should be no problem. Will check it tonight.

**Comment by mpfeil** [comment]
Now the button is added to the exisitng button group

**Comment by sindresorhus** [comment]
Thank you! :)

I published a new version.

**Pull request closed without merging**
